version: 0.2  
phases:
  build:
    commands:
      - echo Build started on 'date'
      - mvn install
  post_build:
    commands:
      - echo Build completed on 'date'
      - mvn package
      - mv target/JenkinsWar.war JenkinsWar.war
artifacts:
  files:
    - '**/*.war'
    artifacts:
      - .ebextensions/**/*
